//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushNotificationServiceTester.ServiceReferenceProd {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ScreenSavingServiceWebRole")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceProd.IPushNotificationService")]
    public interface IPushNotificationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushNotificationService/GetData", ReplyAction="http://tempuri.org/IPushNotificationService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushNotificationService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IPushNotificationService/GetDataUsingDataContractResponse")]
        PushNotificationServiceTester.ServiceReferenceProd.CompositeType GetDataUsingDataContract(PushNotificationServiceTester.ServiceReferenceProd.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushNotificationService/NotifyChannelByUri", ReplyAction="http://tempuri.org/IPushNotificationService/NotifyChannelByUriResponse")]
        string NotifyChannelByUri(string channelUri, string notificationType, string notificationContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushNotificationService/NotifyUser", ReplyAction="http://tempuri.org/IPushNotificationService/NotifyUserResponse")]
        string NotifyUser(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushNotificationService/RegisterNotificationChannel", ReplyAction="http://tempuri.org/IPushNotificationService/RegisterNotificationChannelResponse")]
        string RegisterNotificationChannel(string userId, string channelUri, string channelExpiration);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPushNotificationServiceChannel : PushNotificationServiceTester.ServiceReferenceProd.IPushNotificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PushNotificationServiceClient : System.ServiceModel.ClientBase<PushNotificationServiceTester.ServiceReferenceProd.IPushNotificationService>, PushNotificationServiceTester.ServiceReferenceProd.IPushNotificationService {
        
        public PushNotificationServiceClient() {
        }
        
        public PushNotificationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PushNotificationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PushNotificationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PushNotificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public PushNotificationServiceTester.ServiceReferenceProd.CompositeType GetDataUsingDataContract(PushNotificationServiceTester.ServiceReferenceProd.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public string NotifyChannelByUri(string channelUri, string notificationType, string notificationContent) {
            return base.Channel.NotifyChannelByUri(channelUri, notificationType, notificationContent);
        }
        
        public string NotifyUser(string userId) {
            return base.Channel.NotifyUser(userId);
        }
        
        public string RegisterNotificationChannel(string userId, string channelUri, string channelExpiration) {
            return base.Channel.RegisterNotificationChannel(userId, channelUri, channelExpiration);
        }
    }
}
