//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 11.0.50522.1
// 
namespace WCFClientRuntimeComponent.ScreenSavingsServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ScreenSavingServiceWebRole")]
    internal partial class CompositeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ScreenSavingsServiceReference.IPushNotificationService")]
    internal interface IPushNotificationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushNotificationService/GetData", ReplyAction="http://tempuri.org/IPushNotificationService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushNotificationService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IPushNotificationService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WCFClientRuntimeComponent.ScreenSavingsServiceReference.CompositeType> GetDataUsingDataContractAsync(WCFClientRuntimeComponent.ScreenSavingsServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushNotificationService/NotifyChannelByUri", ReplyAction="http://tempuri.org/IPushNotificationService/NotifyChannelByUriResponse")]
        System.Threading.Tasks.Task<string> NotifyChannelByUriAsync(string channelUri, string notificationType, string notificationContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushNotificationService/NotifyUser", ReplyAction="http://tempuri.org/IPushNotificationService/NotifyUserResponse")]
        System.Threading.Tasks.Task<string> NotifyUserAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPushNotificationService/RegisterNotificationChannel", ReplyAction="http://tempuri.org/IPushNotificationService/RegisterNotificationChannelResponse")]
        System.Threading.Tasks.Task<string> RegisterNotificationChannelAsync(string userId, string channelUri, string channelExpiration);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IPushNotificationServiceChannel : WCFClientRuntimeComponent.ScreenSavingsServiceReference.IPushNotificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class PushNotificationServiceClient : System.ServiceModel.ClientBase<WCFClientRuntimeComponent.ScreenSavingsServiceReference.IPushNotificationService>, WCFClientRuntimeComponent.ScreenSavingsServiceReference.IPushNotificationService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PushNotificationServiceClient() : 
                base(PushNotificationServiceClient.GetDefaultBinding(), PushNotificationServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPushNotificationService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PushNotificationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PushNotificationServiceClient.GetBindingForEndpoint(endpointConfiguration), PushNotificationServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PushNotificationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PushNotificationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PushNotificationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PushNotificationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PushNotificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public System.Threading.Tasks.Task<WCFClientRuntimeComponent.ScreenSavingsServiceReference.CompositeType> GetDataUsingDataContractAsync(WCFClientRuntimeComponent.ScreenSavingsServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public System.Threading.Tasks.Task<string> NotifyChannelByUriAsync(string channelUri, string notificationType, string notificationContent) {
            return base.Channel.NotifyChannelByUriAsync(channelUri, notificationType, notificationContent);
        }
        
        public System.Threading.Tasks.Task<string> NotifyUserAsync(string userId) {
            return base.Channel.NotifyUserAsync(userId);
        }
        
        public System.Threading.Tasks.Task<string> RegisterNotificationChannelAsync(string userId, string channelUri, string channelExpiration) {
            return base.Channel.RegisterNotificationChannelAsync(userId, channelUri, channelExpiration);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPushNotificationService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPushNotificationService)) {
                return new System.ServiceModel.EndpointAddress("http://screensavings.cloudapp.net/PushNotificationService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return PushNotificationServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPushNotificationService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return PushNotificationServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPushNotificationService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IPushNotificationService,
        }
    }
}
